import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar'
import Footer from './components/footer'
import Sidebar from './components/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Coinbit',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full absolute top-5  px-28 z-50 ">
          {/*<Navbar />*/}
        </div>
        <div className='flex'>
          <Sidebar />
          {children}
        </div>
         {/*<Footer />*/}
      </body>
    </html>
  )
}
