"use client";
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './navbar'
import Footer from './components/footer'
import Sidebar from './components/sidebar'
import {app} from ".//firebase"
import {
  RecoilRoot,
} from 'recoil';

const inter = Inter({ subsets: ['latin'] })

{/*export const metadata = {
  title: 'Coinbit',
  description: 'Generated by create next app',
}*/}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" overflow-x-hidden ">
      <RecoilRoot>
        <div className="w-full absolute top-5  px-24 max-[875px]:px-10 max-[700px]:px-5 max-[420px]:pl-0 z-50 ">
         <Navbar />
        </div>
        <div className=''>
          {children}
        </div>
         <Footer />
        </RecoilRoot>
      </body>
    </html>
  )
}
